// (C) Copyright 1997 by Autodesk, Inc. 
//
// Permission to use, copy, modify, and distribute this software in
// object code form for any purpose and without fee is hereby granted, 
// provided that the above copyright notice appears in all copies and 
// that both that copyright notice and the limited warranty and
// restricted rights notice below appear in all supporting 
// documentation.
//
// AUTODESK PROVIDES THIS PROGRAM "AS IS" AND WITH ALL FAULTS. 
// AUTODESK SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR USE.  AUTODESK, INC. 
// DOES NOT WARRANT THAT THE OPERATION OF THE PROGRAM WILL BE
// UNINTERRUPTED OR ERROR FREE.
//
// Use, duplication, or disclosure by the U.S. Government is subject to 
// restrictions set forth in FAR 52.227-19 (Commercial Computer
// Software - Restricted Rights) and DFAR 252.227-7013(c)(1)(ii)
// (Rights in Technical Data and Computer Software), as applicable.
//
//

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pack.rc
//
#define IDS_XREF                        1
#define IDS_IMAGE                       2
#define IDBROWSE                        3
#define IDS_FONTS                       3
#define IDS_MISCELANEOUS                4
#define IDREPORT                        5
#define IDS_TOTAL_SIZE                  5
#define IDS_ERR_RAS_DICT                6
#define IDS_CANT_LOCATE                 7
#define IDS_ERROR_OPENING               8
#define IDS_CREATE_ON                   9
#define IDS_MODIFIED                    10
#define IDS_CANT_CREATE                 11
#define IDS_COPYING_FILE                12
#define IDS_COPY_CANCEL                 13
#define IDS_COPY_COMPLETE               14
#define IDS_EXTREF_REP1                 15
#define IDS_IMAGE_REP2                  16
#define IDS_FONTS_REP3                  17
#define IDS_MISC_REP4                   18
#define IDS_CANT_LOCATE_REP5            19
#define IDS_NOTES_REP6                  20
#define IDS_BAD_UNC                     21
#define IDS_DIR_FNAME_EXIST             22
#define IDS_PATH_NOT_FOUND              23
#define IDS_SHX1_REP7                   24
#define IDS_SHX2_REP8                   25
#define IDS_SHX3_REP9                   26
#define IDS_SHX4_REP10                  27
#define IDS_PFB1_REP11                  28
#define IDS_PFB2_REP12                  29
#define IDS_PFB3_REP13                  30
#define IDS_PFB4_REP14                  31
#define IDS_PFB5_REP15                  32
#define IDS_PFB6_REP16                  33
#define IDS_PFB7_REP17                  34
#define IDS_PFB8_REP18                  35
#define IDS_PFB9_REP19                  36
#define IDS_PFB10_REP20                 37
#define IDS_TTF1_REP21                  38
#define IDS_TTF2_REP22                  39
#define IDS_TTF3_REP23                  40
#define IDS_TTF4_REP24                  41
#define IDS_TTF5_REP25                  42
#define IDS_TTF6_REP26                  43
#define IDS_TTF7_REP27                  44
#define IDS_MAP1_REP28                  45
#define IDS_MAP2_REP29                  46
#define IDS_MAP3_REP30                  47
#define IDS_MAP4_REP31                  48
#define IDS_MAP5_REP32                  49
#define IDS_ALT1_REP33                  50
#define IDS_ALT2_REP34                  51
#define IDS_ALT3_REP35                  52
#define IDS_ALT4_REP36                  53
#define IDS_ALT5_REP37                  54
#define IDS_ALT6_REP38                  55
#define IDS_NOT_ENOUGH_DISK             56
#define IDS_CANNOT_GET_DISK             57
#define LIST_FILENAME                   58
#define LIST_FILESIZE                   59
#define LIST_FILEDATE                   60
#define LIST_VERSION                    61
#define IDS_NO_MEM_TO_PRINT             62
#define IDS_MEM_TO_SAVE                 63
#define IDS_NO_PERMISSION_TO_WRITE      64
#define IDD_DEPEND_DLG                  129
#define IDI_DWG                         129
#define IDI_XREF                        130
#define IDI_FONTS                       131
#define IDI_IMAGE                       132
#define IDD_REPLACE                     140
#define IDD_CREATEDIR                   141
#define IDD_REPORT                      145
#define IDD_SAVEDWG                     147
#define IDD_PATHDLG                     149
#define IDB_SENDICONS                   150
#define IDR_ACCELERATOR1                152
#define IDR_ACCELSEND                   152
#define IDB_Alert                       154
#define IDC_DEPENDTREE                  1000
#define IDC_PATH                        1001
#define IDCOPY                          1004
#define IDC_STATUS                      1006
#define IDYESALL                        1010
#define IDC_FileE                       1011
#define IDC_FileR                       1012
#define IDC_FileESize                   1013
#define IDC_FileRSize                   1014
#define IDC_REPORT                      1022
#define IDC_DIRNAME                     1023
#define IDREPORTPRINT                   1024
#define psh1                            0x0400
#define psh2                            0x0401
#define IDC_DWGNAME                     1025
#define psh3                            0x0402
#define IDC_MSG2                        1026
#define psh4                            0x0403
#define IDC_MSG1                        1027
#define IDC_CHECK1                      1027
#define IDC_SUBDIR                      1027
#define psh5                            0x0404
#define IDSAVE                          1028
#define IDC_DEPENDLIST                  1031
#define IDC_HOTKEY1                     1035
#define psh15                           0x040e
#define psh16                           0x040f
#define chx1                            0x0410
#define chx2                            0x0411
#define chx3                            0x0412
#define IDC_LIST_VIEW                   1050
#define IDC_TREE_VIEW                   1051
#define stc1                            0x0440
#define stc2                            0x0441
#define stc3                            0x0442
#define stc4                            0x0443
#define stc5                            0x0444
#define stc6                            0x0445
#define lst1                            0x0460
#define IDC_TOGGLE_BUTTON_POSITION      1121
#define lst2                            0x0461
#define lst3                            0x0462
#define cmb1                            0x0470
#define cmb2                            0x0471
#define cmb3                            0x0472
#define edt1                            0x0480
#define edt2                            0x0481
#define edt3                            0x0482
#define IDC_STATIC0                     2000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
