// (C) Copyright 1996 by Autodesk, Inc. 
//
// Permission to use, copy, modify, and distribute this software in
// object code form for any purpose and without fee is hereby granted, 
// provided that the above copyright notice appears in all copies and 
// that both that copyright notice and the limited warranty and
// restricted rights notice below appear in all supporting 
// documentation.
//
// AUTODESK PROVIDES THIS PROGRAM "AS IS" AND WITH ALL FAULTS. 
// AUTODESK SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR USE.  AUTODESK, INC. 
// DOES NOT WARRANT THAT THE OPERATION OF THE PROGRAM WILL BE
// UNINTERRUPTED OR ERROR FREE.
//
// Use, duplication, or disclosure by the U.S. Government is subject to 
// restrictions set forth in FAR 52.227-19 (Commercial Computer
// Software - Restricted Rights) and DFAR 252.227-7013(c)(1)(ii)
// (Rights in Technical Data and Computer Software), as applicable.
//
#ifndef __POLYENU_H__
#define __POLYENU_H__

#define IDH_VB_REFERENCE               		0x10001
#define IDH_VB_FUNCTIONS               		0x10002
#define IDH_VB_METHODS                	 	0x10003
#define IDH_VB_OBJECTS                 		0x10004
#define IDH_VB_PROPERTIES              		0x10005

#define IDH_POLY_NUM_SIDES                	0x11011
#define IDH_POLY_CENTER            			0x11012
#define IDH_POLY_START               		0x11013
#define IDH_POLY_NORMAL                		0x11014
#define IDH_POLY_NAME            			0x11015
#define IDH_POLY_INITALL               		0x11016

#endif // __POLYENU_H__
