//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by modeless.rc
//
#define DbmodDlg                        101
//#define IDCLOSE                         1000
#define IDC_WHAT                        1001
#define IDC_EDIT_CLASS                  1002
#define IDC_EDIT_OBJID                  1003
#define IDC_EDIT_HANDLE                 1004
#define IDC_DRAW_CIRCLE                 1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
