//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by loadApp.rc
//
#define IDLOAD                          3
#define IDUNLOAD                        4
#define IDBROWSE                        5
#define IDD_LOADAPP                     129
#define IDR_LATOOLBAR                   149
#define IDC_STATIC_CURRAPP              1000
#define IDC_STATIC_LOADEDAPP            1001
#define IDC_COMBO_CURRAPP               1002
#define IDC_LIST_LOADED_APP             1003
#define IDC_VIEWALL                     1004
#define IDC_REMOVE                      1005
#define IDC_TITLE                       1006
#define IDC_HIDE                        1008
#define IDC_UNHIDE                      1009
#define ID_LCA                          32770
#define ID_ULCS                         32771
#define ID_LADIA                        32772
#define ID_TITLE                        32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
