// (C) Copyright 1996 by Autodesk, Inc. 
//
// Permission to use, copy, modify, and distribute this software in
// object code form for any purpose and without fee is hereby granted, 
// provided that the above copyright notice appears in all copies and 
// that both that copyright notice and the limited warranty and
// restricted rights notice below appear in all supporting 
// documentation.
//
// AUTODESK PROVIDES THIS PROGRAM "AS IS" AND WITH ALL FAULTS. 
// AUTODESK SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR USE.  AUTODESK, INC. 
// DOES NOT WARRANT THAT THE OPERATION OF THE PROGRAM WILL BE
// UNINTERRUPTED OR ERROR FREE.
//
// Use, duplication, or disclosure by the U.S. Government is subject to 
// restrictions set forth in FAR 52.227-19 (Commercial Computer
// Software - Restricted Rights) and DFAR 252.227-7013(c)(1)(ii)
// (Rights in Technical Data and Computer Software), as applicable.
//
// COMMAND.CC 
//
// DESCRIPTION:
//
// This file contains the command interface code for Arx sample app -
// POLYSAMP.


#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <math.h>

#include "adslib.h"
#include "acestext.h"
#include "dbents.h"
#include "dbregion.h"
#include "dbsol3d.h"

#include "gepnt3d.h"

#include "poly.h"
#include "polyjig.h"
#include "util.h"

struct PolyEdit
{
    enum EditMode 
    { 
        kGrow     =  0,
        kShrink   =  1,
        kMore     =  2,
        kLess     =  3,
        kThicken  =  4,
        kFlatten  =  5,
        kName     =  6
	};
};

// static functions used in this file.

static Acad::ErrorStatus    getEditOption(char* option);

static Acad::ErrorStatus    growPoly	(AsdkPoly* poly);
static Acad::ErrorStatus    shrinkPoly	(AsdkPoly* poly);
static Acad::ErrorStatus    morePoly	(AsdkPoly* poly);
static Acad::ErrorStatus    lessPoly	(AsdkPoly* poly);
static Acad::ErrorStatus    thickenPoly (AsdkPoly* poly);
static Acad::ErrorStatus    flattenPoly (AcDb3dSolid* solid);
static Acad::ErrorStatus    namePoly	(AsdkPoly* poly);
static Acad::ErrorStatus    stylePoly	(AsdkPoly* poly);
static Acad::ErrorStatus    setPolyArea (AsdkPoly* poly, double area);
static Acad::ErrorStatus    replaceEntity(AcDbEntity*& thisOne, 
                                          AcDbEntity*  with);

static PolyEdit::EditMode   eMode = PolyEdit::kGrow;
static Adesk::Boolean	    done = Adesk::kFalse;

static AcGePoint3d   savedCenter;
static AcGePoint3d   savedStartPoint;
static int	     savedNumSides;
static AcGeVector3d  savedNormal;
static char	     savedName[133];

static AcDbEntity   *ent = NULL;

// Also used in hilit.cc
//
Adesk::Boolean interrupted = Adesk::kFalse;

// Also used in hilit.cc and transact.cc
//
Acad::ErrorStatus
getYOrN(char* promptStr, Adesk::Boolean defaultY, Adesk::Boolean& yes);


// Invoked by the command - DRAGPOLY
//
DLLIMPEXP void 
dragPolyCommand()
{
    int nSides = 0;
    
    ads_point center, startPt, normal;
    
    if (ads_getpoint(NULL, "\nLocate center of polygon: ", center) != RTNORM)
        return;
    
    char nameBuf[133];
    if (ads_getstring(Adesk::kTrue, "\nEnter polygon name: ", nameBuf) != RTNORM)
        return;
    
    AcDbObjectId tsId = 0;
    char styleBuf[133];
    if (ads_getstring(Adesk::kTrue, "\nEnter text style: ", styleBuf) != RTNORM)
        return;
    
    if (styleBuf[0] != '\0' && rx_getTextStyleId(styleBuf, acdbCurDwg(), tsId)
        != Acad::eOk)
    {
        ads_printf("\nInvalid text style name");
        return;
    }
    
    
    // Set the normal to the plane of the polygon to be the same as the
    // z direction of the current ucs, i.e. (0, 0, 1) since we also got the
    // center and start point in the current UCS. (ads_getpoint() returns in
    // the current UCS.)
    
    normal[X] = 0.0; normal[Y] = 0.0; normal[Z] = 1.0;
    
    rx_uc2wc(center, center, Adesk::kFalse);
    rx_uc2wc(startPt, startPt, Adesk::kFalse);
    rx_uc2wc(normal, normal, Adesk::kTrue);
    
    AcGePoint3d cen = asPnt3d(center), start = asPnt3d(startPt);
    AcGeVector3d norm = asVec3d(normal);
    
    AsdkPolyJig*  pJig = new AsdkPolyJig();
    pJig->acquire(cen, norm, nameBuf, tsId);
    
    delete pJig;
}

// Invoked by the command - POLY
//
DLLIMPEXP void 
polyCommand()
{
    int nSides = 0;
    
    while (nSides < 3) {
        
        ads_initget(INP_NNEG, "");
        switch (ads_getint("\nEnter number of sides: ", &nSides)) {
            
        case RTNORM:
            if (nSides < 3)
                ads_printf("\nNeed at least 3 sides.");
            break;
        default:
            return;
        }
    }
    
    ads_point center, startPt, normal;
    
    if (ads_getpoint(NULL, "\nLocate center of polygon: ", center) != RTNORM)
        return;
    
    startPt[0] = center[0]; startPt[1] = center[1]; startPt[2] = center[2];
    while (asPnt3d(startPt) == asPnt3d(center)) {
        switch (ads_getpoint(center, "\nLocate start point of polygon: ", 
            startPt)) {
        case RTNORM:
            if (asPnt3d(center) == asPnt3d(startPt))
                ads_printf("\nPick a point different from the center.");
            break;
        default:
            return;
        }
    }
    
    char nameBuf[133];
    if (ads_getstring(Adesk::kTrue, "\nEnter polygon name: ", nameBuf) != RTNORM)
        return;
    
    AcDbObjectId tsId = 0;
    char styleBuf[133];
    if (ads_getstring(Adesk::kTrue, "\nEnter text style: ", styleBuf) != RTNORM)
        return;
    
    if (styleBuf[0] != '\0' && rx_getTextStyleId(styleBuf, acdbCurDwg(), tsId)
        != Acad::eOk)
    {
        ads_printf("\nInvalid text style name");
        return;
    }
    
    
    // Set the normal to the plane of the polygon to be the same as the
    // z direction of the current ucs, i.e. (0, 0, 1) since we also got the
    // center and start point in the current UCS. (ads_getpoint() returns in
    // the current UCS.)
    
    normal[X] = 0.0; normal[Y] = 0.0; normal[Z] = 1.0;
    
    rx_uc2wc(center, center, Adesk::kFalse);
    rx_uc2wc(startPt, startPt, Adesk::kFalse);
    rx_uc2wc(normal, normal, Adesk::kTrue);
    
    AcGePoint3d cen = asPnt3d(center), start = asPnt3d(startPt);
    AcGeVector3d norm = asVec3d(normal);
    
    AsdkPoly* poly = new AsdkPoly(cen, start, nSides, norm, nameBuf, tsId);
    
    poly->setDatabaseDefaults(acdbCurDwg());
    postToDb(poly);
}


DLLIMPEXP void 
polyeditCommand()
{
    interrupted = Adesk::kFalse;
    Acad::ErrorStatus es = Acad::eOk;
    
    AcDbFullSubentPath nullSub;
    
    // Select an AsdkPoly entity.
    
    AsdkPoly	 *poly = NULL;
    AcDb3dSolid  *solid = NULL;
    AcDbObjectId  objId;
    
    ads_name	  ename;
    ads_point     ptres;
    
    for (;;) {
        
        switch (ads_entsel("Select a poly: ", ename, ptres)) {
            
        case RTNORM:
            
            AOK(acdbGetObjectId(objId, ename));
            
            AOK(acdbOpenAcDbEntity(ent, objId, AcDb::kForRead));
            assert(ent != NULL);
            
            poly = AsdkPoly::cast(ent);
            if (poly == NULL) {
                ads_printf("\nNot a polygon.");
                AOK(ent->close());
                continue;
            }
            
            break;
            
        case RTNONE:
        case RTCAN:
            return;
        default:
            continue;
        }
        break;
    }
    
    // Now we have a polygon. Start editing it.
    
    char option[256];
    eMode = PolyEdit::kGrow;
    
    done = Adesk::kFalse;
    interrupted = Adesk::kFalse;
    
    while (!done && !interrupted) {
        
        AOK(getEditOption(option));
        
        if (strcmp(option, "Grow") == 0) {
            
            if (!ent->isKindOf(AsdkPoly::desc())) {
                ads_printf("\nNot Applicable");
                continue;
            }
            eMode = PolyEdit::kGrow;
            AOK(growPoly(poly));
            
        } else if (strcmp(option, "Shrink") == 0) {
            
            if (!ent->isKindOf(AsdkPoly::desc())) {
                ads_printf("\nNot Applicable");
                continue;
            }
            eMode = PolyEdit::kShrink;
            AOK(shrinkPoly(poly));
            
        } else if (strcmp(option, "More") == 0) {
            
            if (!ent->isKindOf(AsdkPoly::desc())) {
                ads_printf("\nNot Applicable");
                continue;
            }
            eMode = PolyEdit::kMore;
            AOK(morePoly(poly));
            
        } else if (strcmp(option, "Less") == 0) {
            
            if (!ent->isKindOf(AsdkPoly::desc())) {
                ads_printf("\nNot Applicable");
                continue;
            }
            eMode = PolyEdit::kLess;
            AOK(lessPoly(poly));
            
        } else if (strcmp(option, "Thicken") == 0) {
            
            if (!ent->isKindOf(AsdkPoly::desc())) {
                ads_printf("\nNot Applicable");
                continue;
            }
            eMode = PolyEdit::kThicken;
            AOK(thickenPoly(poly));
            
            solid = AcDb3dSolid::cast(ent);
            assert(solid != NULL);
            poly = NULL;
            
            
            solid->draw();
            
        } else if (strcmp(option, "Flatten") == 0) {
            
            if (!ent->isKindOf(AcDb3dSolid::desc())) {
                ads_printf("\nNot Applicable");
                continue;
            }
            eMode = PolyEdit::kFlatten;
            AOK(flattenPoly(solid));
            
            poly = AsdkPoly::cast(ent);
            assert(poly != NULL);
            solid = NULL;
            
            
        } else if (strcmp(option, "Name") == 0) {
            
            if (!ent->isKindOf(AsdkPoly::desc())) {
                ads_printf("\nNot Applicable");
                continue;
            }
            eMode = PolyEdit::kName;
            Acad::ErrorStatus es;
            if ((es = namePoly(poly)) != Acad::eOk) {
                ads_printf("\nError setting Poly's name. Error: %s",
                    acadErrorStatusText(es));
                done = Adesk::kTrue;
                continue;
            }
            if ((es = stylePoly(poly)) != Acad::eOk) {
                ads_printf("\nError setting Poly's text style. Error: %s",
                    acadErrorStatusText(es));
                done = Adesk::kTrue;
                continue;
            }
        } else if (strcmp(option, "EXit") == 0) {
            done = Adesk::kTrue;
        } else {
            done = Adesk::kTrue;
        }
        
    }
    
    // Close the entity corresponding to the open for read right
    // after selection.
    
    AOK(ent->close());
}


static Acad::ErrorStatus
getEditOption(char* option)
{
    Acad::ErrorStatus es = Acad::eOk;
    int 	      as = RTNORM;
    
    char promptStr[256];
    
    ads_initget(0, "Grow Shrink More Less Thicken Flatten Name EXit X");
    
    switch (eMode) {
        
    case PolyEdit::kGrow:
        
        sprintf(promptStr, 
            "\nGrow/Shrink/More/Less/Thicken/Flatten/Name/eXit/<Grow>: ");
        break;
        
    case PolyEdit::kShrink:
        
        sprintf(promptStr, 
            "\nGrow/Shrink/More/Less/Thicken/Flatten/Name/eXit/<Shrink>: ");
        break;
        
    case PolyEdit::kMore:
        
        sprintf(promptStr, 
            "\nGrow/Shrink/More/Less/Thicken/Flatten/Name/eXit/<More>: ");
        break;
        
    case PolyEdit::kLess:
        
        sprintf(promptStr, 
            "\nGrow/Shrink/More/Less/Thicken/Flatten/Name/eXit/<Less>: ");
        break;
        
    case PolyEdit::kThicken:
        
        sprintf(promptStr, 
            "\nGrow/Shrink/More/Less/Thicken/Flatten/Name/eXit/<Thicken>: ");
        break;
        
    case PolyEdit::kFlatten:
        
        sprintf(promptStr, 
            "\nGrow/Shrink/More/Less/Thicken/Flatten/Name/eXit/<Flatten>: ");
        break;
        
    case PolyEdit::kName:
        
        sprintf(promptStr, 
            "\nGrow/Shrink/More/Less/Thicken/Flatten/Name/eXit/<Name>: ");
        break;

    default:
        // Should never happen!
        //
        assert(0);
        return Acad::eInvalidInput;
    }
    
    as = ads_getkword(promptStr, option);
    
    switch (as) {
    case RTNORM:
        
        if (strcmp(option, "X") == 0) {
            strcpy(option, "EXit");
        }
        break;
    case RTNONE:
        if (eMode == PolyEdit::kGrow) {
            strcpy(option, "Grow");
        } else if (eMode == PolyEdit::kShrink) {
            strcpy(option, "Shrink");
        } else if (eMode == PolyEdit::kMore) {
            strcpy(option, "More");
        } else if (eMode == PolyEdit::kLess) {
            strcpy(option, "Less");
        } else if (eMode == PolyEdit::kThicken) {
            strcpy(option, "Thicken");
        } else if (eMode == PolyEdit::kFlatten) {
            strcpy(option, "Flatten");
        } else if (eMode == PolyEdit::kName) {
            strcpy(option, "Name");
        }
        break;
    case RTCAN:
        interrupted = Adesk::kTrue;
        break;
    default:
        done = Adesk::kTrue;
        break;
    }
    
    return es;
}



// Increases the area of the polygon by one quarter of its original
// area. New area = 1.25 * old area

static Acad::ErrorStatus 
growPoly(AsdkPoly* poly)
{
    Acad::ErrorStatus es = Acad::eOk;
    
    double oldArea;
    if ((es = poly->getArea(oldArea)) != Acad::eOk) {
        return es;
    }
    
    double area = oldArea * 1.25;
    
    if ((es = setPolyArea(poly, area)) != Acad::eOk) {
        return es;
    }
    
    return es;
}


// Decrease the area of the polygon by twenty percent.
// New area = 0.8 * old area. That way "Grow" followed by a "Shrink"
// will bring the polygon back to its original size.

static Acad::ErrorStatus 
shrinkPoly(AsdkPoly* poly)
{
    Acad::ErrorStatus es = Acad::eOk;
    
    double oldArea;
    if ((es = poly->getArea(oldArea)) != Acad::eOk) {
        return es;
    }
    
    double area = oldArea * 0.8;
    
    if ((es = setPolyArea(poly, area)) != Acad::eOk) {
        return es;
    }
    
    return es;
}


// Increases the number of sides of the polygon by one.

static Acad::ErrorStatus 
morePoly(AsdkPoly* poly)
{
    Acad::ErrorStatus es = Acad::eOk;
    
    int numSides = poly->numSides() + 1;
    
    if ((es = poly->upgradeOpen()) != Acad::eOk) {
        return es;
    }
    if ((es = poly->setNumSides(numSides)) != Acad::eOk) {
        poly->downgradeOpen();
        return es;
    }
    if ((es = poly->downgradeOpen()) != Acad::eOk) {
        return es;
    }
    
    return es;
}

// Decreases the number of sides of the polygon by one.

static Acad::ErrorStatus 
lessPoly(AsdkPoly* poly)
{
    Acad::ErrorStatus es = Acad::eOk;
    
    if (poly->numSides() == 3) {
        ads_printf("\nThat's it.");
        return es;
    }
    int numSides = poly->numSides()  - 1;
    
    if ((es = poly->upgradeOpen()) != Acad::eOk) {
        return es;
    }
    if ((es = poly->setNumSides(numSides)) != Acad::eOk) {
        poly->downgradeOpen();
        return es;
    }
    if ((es = poly->downgradeOpen()) != Acad::eOk) {
        return es;
    }
    
    return es;
}


// Extrudes the region to a height that is one-fourth the perimeter.

static Acad::ErrorStatus 
thickenPoly(AsdkPoly* poly)
{
    Acad::ErrorStatus es = Acad::eOk;
    int i;
    AcDbVoidPtrArray lines;
    AcDbVoidPtrArray regions;
    
    // Explode to a set of lines
    //
    if ((es = poly->explode(lines)) != Acad::eOk) {
        for (i = 0; i < lines.length(); i++) {
            delete (AcRxObject*)lines[i];
        }
        for (i = 0; i < regions.length(); i++) {
            delete (AcRxObject*)regions[i];
        }
        return es;
    }
    
    // Create a region from the set of lines.
    //
    if ((es = AcDbRegion::createFromCurves(lines, regions)) != Acad::eOk) {
        for (i = 0; i < lines.length(); i++) {
            delete (AcRxObject*)lines[i];
        }
        for (i = 0; i < regions.length(); i++) {
            delete (AcRxObject*)regions[i];
        }
        return es;
    }
    assert(regions.length() == 1);
    AcDbRegion* region = AcDbRegion::cast((AcRxObject*)regions[0]);
    assert(region != NULL);
    
    // Extrude the region to create a solid.
    //
    double height;
    if ((es = poly->getDistAtParam(6.28318530717958647692, height))
        != Acad::eOk)
    {
        for (i = 0; i < lines.length(); i++) {
            delete (AcRxObject*)lines[i];
        }
        for (i = 0; i < regions.length(); i++) {
            delete (AcRxObject*)regions[i];
        }
        return es;
    }
    height *= 0.25;
    
    AcDb3dSolid* solid = new AcDb3dSolid;
    assert(solid != NULL);
    if ((es = solid->extrude(region, height, 0.0)) != Acad::eOk) {
        delete solid;
        for (i = 0; i < lines.length(); i++) {
            delete (AcRxObject*)lines[i];
        }
        for (i = 0; i < regions.length(); i++) {
            delete (AcRxObject*)regions[i];
        }
        return es;
    }
    
    // Save up the data to flatten the solid.
    //
    savedCenter     = poly->center();
    savedStartPoint = poly->startPoint();
    savedNumSides   = poly->numSides();
    savedNormal     = poly->normal();

    // Copy the poly name
    //
    strcpy(savedName, poly->name());
    
    // Now we have a solid. Change the entity to be this solid
    
    if ((es = solid->setPropertiesFrom(poly)) != Acad::eOk) {
        delete solid;
        for (i = 0; i < lines.length(); i++) {
            delete (AcRxObject*)lines[i];
        }
        for (i = 0; i < regions.length(); i++) {
            delete (AcRxObject*)regions[i];
        }
        return es;
    }
    
    ent = poly;
    if ((es = ent->upgradeOpen()) != Acad::eOk) {
        delete solid;
        for (i = 0; i < lines.length(); i++) {
            delete (AcRxObject*)lines[i];
        }
        for (i = 0; i < regions.length(); i++) {
            delete (AcRxObject*)regions[i];
        }
        return es;
    }
    es = replaceEntity(ent, solid);
    if ((es != Acad::eOk) && (es != Acad::eObjectToBeDeleted)) {
        ent->downgradeOpen();
        delete solid; 
        for (i = 0; i < lines.length(); i++) {
            delete (AcRxObject*)lines[i];
        }
        for (i = 0; i < regions.length(); i++) {
            delete (AcRxObject*)regions[i];
        }
        return es;
    }
    es = ent->downgradeOpen();
    
    for (i = 0; i < lines.length(); i++) {
        delete (AcRxObject*)lines[i];
    }
    for (i = 0; i < regions.length(); i++) {
        delete (AcRxObject*)regions[i];
    }
    return es;
}


static Acad::ErrorStatus 
flattenPoly(AcDb3dSolid* solid)
{
    Acad::ErrorStatus es = Acad::eOk;
    
    AsdkPoly* poly = new AsdkPoly(savedCenter, savedStartPoint,
        savedNumSides, savedNormal, savedName);
    
    // Change the entity to be the poly. 
    
    if ((es = poly->setPropertiesFrom(solid)) != Acad::eOk) {
        delete poly;
        return es;
    }
    
    ent = solid;
    if ((es = ent->upgradeOpen()) != Acad::eOk) {
        delete poly;
        return es;
    }
    es = replaceEntity(ent, poly);
    if((es != Acad::eOk) && (es != Acad::eObjectToBeDeleted)) {
        ent->downgradeOpen();
        delete poly; 
        return es;
    }
    if ((es = ent->downgradeOpen()) != Acad::eOk) {
        return es;
    }
    
    return es;
}


// Solicit a new name for the polygon

static Acad::ErrorStatus 
namePoly(AsdkPoly* poly)
{
    Acad::ErrorStatus es = Acad::eOk;
    
    char nameBuf[133];
    if (ads_getstring(Adesk::kTrue, "\nEnter new name: ", nameBuf) == RTNORM) {
        if ((es = poly->upgradeOpen()) != Acad::eOk) {
            return es;
        }
        if ((es = poly->setName(nameBuf)) != Acad::eOk) {
            poly->downgradeOpen();
            return es;
        }
        
        return poly->downgradeOpen();
    } else
        return Acad::eInvalidInput;
}


// Solicit a new text style for the polygon

static Acad::ErrorStatus 
stylePoly(AsdkPoly* poly)
{
    Acad::ErrorStatus es = Acad::eOk;
    
    char nameBuf[133];
    int as;
    if ((as = ads_getstring(Adesk::kTrue, "\nEnter new text style: ", 
        nameBuf)) == RTNORM) {
        // NULL string.
        if (strlen(nameBuf) == 0)
            return Acad::eOk;
        AcDbObjectId tsId;
        if ((es = rx_getTextStyleId(nameBuf, acdbCurDwg(), tsId)) != Acad::eOk)
            return es;
        if ((es = poly->upgradeOpen()) != Acad::eOk) {
            return es;
        }
        if ((es = poly->setTextStyle(tsId)) != Acad::eOk) {
            poly->downgradeOpen();
            return es;
        }
        return poly->downgradeOpen();
    } else if (as == RTCAN)
        return Acad::eOk;
    else
        return Acad::eInvalidInput;
}


static Acad::ErrorStatus 
setPolyArea(AsdkPoly* poly, double area)
{
    Acad::ErrorStatus es = Acad::eOk;
    
    double theta = 3.14159265358979323846 * 0.5 - 3.14159265358979323846 / poly->numSides();
    double circumRadius = sqrt
        ((2.0 * area) / (poly->numSides() * sin(2.0 * theta)));
    
    if (circumRadius < 1.0e-10) {
        ads_printf("\nThat's it.");
        return Acad::eOk;
    }
    
    AcGeVector3d vec = poly->startPoint() - poly->center();
    vec.normalize();
    vec *= circumRadius;
    AcGePoint3d startPt = poly->center() + vec;
    
    if ((es = poly->upgradeOpen()) != Acad::eOk) {
        return es;
    }
    if ((es = poly->setStartPoint(startPt)) != Acad::eOk) {
        poly->downgradeOpen();
        return es;
    }
    if ((es = poly->downgradeOpen()) != Acad::eOk) {
        return es;
    }
    
    return es;
}


//  Replace "thisOne" with "with" in the database.  As currently written,
//  "thisOne" must be open for write on entry.  "with" is non-database-
//  resident, and on return, it is open for write (and is in the
//  database).  On success, "thisOne" is set equal with "with".
//
static Acad::ErrorStatus 
replaceEntity(AcDbEntity*& thisOne, AcDbEntity*  with)
{
    Acad::ErrorStatus es = thisOne->handOverTo(with);
    if (es == Acad::eObjectToBeDeleted) {
        delete thisOne;
        thisOne = with;
    }
    return es;
}


Acad::ErrorStatus
getYOrN(char* promptStr, Adesk::Boolean defaultY, Adesk::Boolean& yes)
{
    char option[256];
    yes = Adesk::kTrue;
    
    ads_initget(0, "Yes No");
    int as = ads_getkword(promptStr, option);
    
    switch (as) {
    case RTNORM:
        if (strcmp(option, "Yes") == 0)
            yes = Adesk::kTrue;
        else
            yes = Adesk::kFalse;
        break;
        
    case RTNONE:
        if (defaultY)
            yes = Adesk::kTrue;
        else
            yes = Adesk::kFalse;
        break;
        
    case RTCAN:
        interrupted = Adesk::kTrue;
        break;
    default:
        break;
    }
    
    return Acad::eOk;
}
